apiVersion: apps/v1
kind: Deployment
metadata:
  name: freetech-webshell
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        image.kubernetes.io/change-trigger: "sha-placeholder"
    spec:
      containers:
        - name: freetech-webshell
          imagePullPolicy: Always
