apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: freetech-webshell-production
resources:
- ../../base
- namespace.yaml
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: ghcr.io/cyrildesch/freetech-webshell
  newName: ghcr.io/cyrildesch/freetech-webshell
  newTag: sha-37f3882
