apiVersion: v1
kind: Service
metadata:
  name: freetech-webshell
  labels:
    app: freetech-webshell
spec:
  selector:
    app: freetech-webshell
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
